/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  // "aws_project_region": process.env.REACT_APP_REGION,
  // "aws_cognito_region": process.env.REACT_APP_REGION,
  // "aws_cognito_identity_pool_id": process.env.REACT_APP_IDENTITYPOOL_ID,
  // "aws_user_pools_id": process.env.REACT_APP_USERPOOL_ID,
  // "aws_user_pools_web_client_id": process.env.REACT_APP_WEBCLIENT_ID
  "aws_project_region": "us-east-1",
  "aws_cognito_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:36618801-f4ca-4fd7-ab5e-da9e373610f6",
  "aws_user_pools_id": "us-east-1_hFOZlr6AQ",
  "aws_user_pools_web_client_id": "1vo8fhcihjf1ijb1fu326uiit8", // Cognito User Pool Web Client ID
};
export default awsmobile;
